spring.application.name=lavapro
spring.datasource.url=${LAVAPRO_DB_URL}
spring.datasource.username=${TODO_DB_USER}
spring.datasource.password=${TODO_DB_PASSWORD}

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
